/**
 * Lighthouse Performance Configuration
 * Comprehensive web vitals and performance testing
 */

const lighthouseConfig = {
  extends: 'lighthouse:default',
  settings: {
    onlyCategories: ['performance'],
    // Simulate slower network and CPU
    throttling: {
      rttMs: 40,
      throughputKbps: 10240,
      cpuSlowdownMultiplier: 1,
      requestLatencyMs: 0,
      downloadThroughputKbps: 0,
      uploadThroughputKbps: 0,
    },
    // Additional performance settings
    emulatedFormFactor: 'desktop',
    internalDisableDeviceScreenEmulation: true,
    formFactor: 'desktop',
    screenEmulation: {
      mobile: false,
      width: 1920,
      height: 1080,
      deviceScaleFactor: 1,
      disabled: false,
    },
    // Performance budgets
    budgets: [
      {
        path: '/*',
        timings: [
          {
            metric: 'first-contentful-paint',
            budget: 1500,
          },
          {
            metric: 'largest-contentful-paint',
            budget: 2500,
          },
          {
            metric: 'cumulative-layout-shift',
            budget: 0.1,
          },
          {
            metric: 'first-input-delay',
            budget: 100,
          },
          {
            metric: 'time-to-interactive',
            budget: 3500,
          },
        ],
        resourceCounts: [
          {
            resourceType: 'script',
            budget: 10,
          },
          {
            resourceType: 'stylesheet',
            budget: 5,
          },
          {
            resourceType: 'image',
            budget: 50,
          },
        ],
        resourceSizes: [
          {
            resourceType: 'script',
            budget: 500000, // 500KB
          },
          {
            resourceType: 'stylesheet',
            budget: 100000, // 100KB
          },
          {
            resourceType: 'total',
            budget: 2000000, // 2MB
          },
        ],
      },
    ],
  },
  passes: [
    {
      passName: 'defaultPass',
      gatherers: [
        'css-usage',
        'js-usage',
        'viewport-dimensions',
        'runtime-exceptions',
        'console-messages',
        'anchor-elements',
        'image-elements',
        'link-elements',
        'meta-elements',
        'script-elements',
        'iframe-elements',
        'form-elements',
        'details-elements',
        'devtools-log',
        'trace',
        'screenshot',
        'full-page-screenshot',
        'source-maps',
        'accessibility',
        'dobetterweb/doctype',
        'dobetterweb/domstats',
        'dobetterweb/optimized-images',
        'dobetterweb/password-inputs-with-prevented-paste',
        'dobetterweb/response-compression',
        'dobetterweb/tags-blocking-first-paint',
        'seo/font-display',
        'seo/embedded-content',
        'seo/robots-txt',
        'seo/tap-targets',
        'seo/font-size',
        'seo/link-text',
        'seo/is-crawlable',
        'seo/hreflang',
        'seo/plugins',
        'seo/canonical',
        'offline-start-url',
        'start-url',
        'security-state',
        'mixed-content',
        'is-on-https',
        'redirects',
        'image-aspect-ratio',
        'image-size-responsive',
        'loading-attr',
        'preload-fonts',
        'robots-txt',
        'service-worker',
        'offline-start-url',
        'start-url',
        'apple-touch-icon',
        'html-has-lang',
        'html-lang-valid',
        'splash-screen',
        'themed-omnibox',
        'viewport',
        'without-javascript',
        'metrics',
        'screenshot',
        'full-page-screenshot',
        'final-screenshot',
        'user-timings',
        'critical-request-chains',
        'main-thread-tasks',
        'metrics',
        'network-analysis',
        'bootup-time',
        'uses-optimized-images',
        'uses-webp-images',
        'uses-text-compression',
        'uses-rel-preconnect',
        'uses-rel-preload',
        'uses-http2',
        'uses-long-cache-ttl',
        'total-byte-weight',
        'offscreen-images',
        'render-blocking-resources',
        'unminified-css',
        'unminified-javascript',
        'unused-css-rules',
        'unused-javascript',
        'uses-responsive-images',
        'efficient-animated-content',
        'duplicated-javascript',
        'legacy-javascript',
        'appcache-manifest',
        'doctype',
        'charset',
        'dom-size',
        'geolocation-on-start',
        'inspector-issues',
        'no-document-write',
        'no-vulnerable-libraries',
        'js-libraries',
        'notification-on-start',
        'object-alt',
        'password-inputs-with-prevented-paste',
        'uses-passive-event-listeners',
        'meta-description',
        'http-status-code',
        'font-display',
        'logical-tab-order',
        'focusable-controls',
        'interactive-element-affordance',
        'managed-focus',
        'focus-traps',
        'custom-controls-labels',
        'custom-controls-roles',
        'visual-order-follows-dom',
        'offscreen-content-hidden',
        'heading-levels',
        'use-landmarks',
      ],
    },
  ],
  audits: [
    'metrics',
    'screenshot',
    'full-page-screenshot',
    'final-screenshot',
    'user-timings',
    'critical-request-chains',
    'redirects',
    'main-thread-tasks',
    'bootup-time',
    'uses-rel-preload',
    'uses-rel-preconnect',
    'font-display',
    'network-analysis',
    'network-rtt',
    'network-server-latency',
    'main-thread-tasks',
    'diagnostics',
    'resource-summary',
    'third-party-summary',
    'third-party-facades',
    'largest-contentful-paint-element',
    'lcp-lazy-loaded',
    'layout-shift-elements',
    'uses-long-cache-ttl',
    'total-byte-weight',
    'offscreen-images',
    'render-blocking-resources',
    'unminified-css',
    'unminified-javascript',
    'unused-css-rules',
    'unused-javascript',
    'uses-optimized-images',
    'uses-text-compression',
    'uses-responsive-images',
    'efficient-animated-content',
    'duplicated-javascript',
    'legacy-javascript',
    'preload-lcp-image',
    'cumulative-layout-shift',
    'server-response-time',
    'speed-index',
    'total-blocking-time',
    'max-potential-fid',
    'cumulative-layout-shift',
    'largest-contentful-paint',
    'first-contentful-paint',
    'first-meaningful-paint',
    'interactive',
    'first-cpu-idle',
    'estimated-input-latency',
  ],
  categories: {
    performance: {
      title: 'Performance',
      auditRefs: [
        { id: 'first-contentful-paint', weight: 10, group: 'metrics' },
        { id: 'largest-contentful-paint', weight: 25, group: 'metrics' },
        { id: 'first-meaningful-paint', weight: 10, group: 'metrics' },
        { id: 'speed-index', weight: 10, group: 'metrics' },
        { id: 'interactive', weight: 10, group: 'metrics' },
        { id: 'first-cpu-idle', weight: 10, group: 'metrics' },
        { id: 'max-potential-fid', weight: 10, group: 'metrics' },
        { id: 'cumulative-layout-shift', weight: 15, group: 'metrics' },
        { id: 'server-response-time', weight: 0, group: 'load-opportunities' },
        { id: 'render-blocking-resources', weight: 0, group: 'load-opportunities' },
        { id: 'uses-responsive-images', weight: 0, group: 'load-opportunities' },
        { id: 'offscreen-images', weight: 0, group: 'load-opportunities' },
        { id: 'unminified-css', weight: 0, group: 'load-opportunities' },
        { id: 'unminified-javascript', weight: 0, group: 'load-opportunities' },
        { id: 'unused-css-rules', weight: 0, group: 'load-opportunities' },
        { id: 'unused-javascript', weight: 0, group: 'load-opportunities' },
        { id: 'uses-optimized-images', weight: 0, group: 'load-opportunities' },
        { id: 'uses-text-compression', weight: 0, group: 'load-opportunities' },
        { id: 'uses-rel-preconnect', weight: 0, group: 'load-opportunities' },
        { id: 'uses-rel-preload', weight: 0, group: 'load-opportunities' },
        { id: 'efficient-animated-content', weight: 0, group: 'load-opportunities' },
        { id: 'duplicated-javascript', weight: 0, group: 'load-opportunities' },
        { id: 'legacy-javascript', weight: 0, group: 'load-opportunities' },
        { id: 'preload-lcp-image', weight: 0, group: 'load-opportunities' },
        { id: 'total-byte-weight', weight: 0, group: 'diagnostics' },
        { id: 'uses-long-cache-ttl', weight: 0, group: 'diagnostics' },
        { id: 'dom-size', weight: 0, group: 'diagnostics' },
        { id: 'critical-request-chains', weight: 0, group: 'diagnostics' },
        { id: 'user-timings', weight: 0, group: 'diagnostics' },
        { id: 'bootup-time', weight: 0, group: 'diagnostics' },
        { id: 'mainthread-work-breakdown', weight: 0, group: 'diagnostics' },
        { id: 'font-display', weight: 0, group: 'diagnostics' },
        { id: 'resource-summary', weight: 0, group: 'diagnostics' },
        { id: 'third-party-summary', weight: 0, group: 'diagnostics' },
        { id: 'third-party-facades', weight: 0, group: 'diagnostics' },
        { id: 'largest-contentful-paint-element', weight: 0, group: 'diagnostics' },
        { id: 'lcp-lazy-loaded', weight: 0, group: 'diagnostics' },
        { id: 'layout-shift-elements', weight: 0, group: 'diagnostics' },
        { id: 'network-analysis', weight: 0, group: 'diagnostics' },
        { id: 'network-rtt', weight: 0, group: 'diagnostics' },
        { id: 'network-server-latency', weight: 0, group: 'diagnostics' },
        { id: 'main-thread-tasks', weight: 0, group: 'diagnostics' },
        { id: 'diagnostics', weight: 0, group: 'diagnostics' },
        { id: 'metrics', weight: 0, group: 'hidden' },
        { id: 'screenshot', weight: 0, group: 'hidden' },
        { id: 'full-page-screenshot', weight: 0, group: 'hidden' },
        { id: 'final-screenshot', weight: 0, group: 'hidden' },
      ],
    },
  },
  groups: {
    metrics: {
      title: 'Metrics',
    },
    'load-opportunities': {
      title: 'Opportunities',
      description: 'These suggestions can help your page load faster. They don\'t [directly affect](https://web.dev/performance-scoring/) the Performance score.',
    },
    diagnostics: {
      title: 'Diagnostics',
      description: 'More information about the performance of your application. These numbers don\'t [directly affect](https://web.dev/performance-scoring/) the Performance score.',
    },
    hidden: {
      title: 'Hidden',
      description: 'These audits are hidden from the report but used internally.',
    },
  },
};

module.exports = lighthouseConfig;