"""Typed wrappers around Supabase-generated Pydantic models.

These helpers expose the schema generated by ``supabase_pydantic`` while
providing a thin compatibility layer for the rest of the codebase. The
auto-generated models make several columns non-nullable even though production
data can contain ``NULL`` values; the wrappers relax those constraints and add a
couple of convenience properties that mirror the legacy dataclass interface.

Whenever the Supabase schema changes, regenerate
``src/atomsAgent/db/generated/fastapi/schema_public_latest.py`` and keep the
wrappers in sync if new fields appear.
"""

from __future__ import annotations

import datetime as _dt
from typing import Any, ClassVar

from pydantic import ConfigDict, Field

from atomsAgent.db.generated.fastapi import schema_public_latest as _schema


class SupabaseSystemPrompt(_schema.SystemPrompt):
    """Relaxed SystemPrompt model that tolerates nullable timestamps."""

    model_config: ClassVar[ConfigDict] = ConfigDict(populate_by_name=True)

    created_at: _dt.datetime | None = None
    updated_at: _dt.datetime | None = None
    priority: int | None = None
    enabled: bool | None = None

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> "SupabaseSystemPrompt":
        return cls.model_validate(row)


class SupabaseMcpConfiguration(_schema.McpConfiguration):
    """Supabase MCP configuration with optional metadata fields."""

    model_config: ClassVar[ConfigDict] = ConfigDict(populate_by_name=True)

    field_type: str | None = Field(default=None, alias="type")
    scope: str | None = None
    created_at: _dt.datetime | None = None
    updated_at: _dt.datetime | None = None
    created_by: str | None = None
    updated_by: str | None = None
    enabled: bool | None = None

    @property
    def type(self) -> str | None:  # pragma: no cover - compatibility shim
        return self.field_type

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> "SupabaseMcpConfiguration":
        return cls.model_validate(row)


class SupabaseMcpOauthTransaction(_schema.McpOauthTransaction):
    """OAuth transaction record with optional fields."""

    model_config: ClassVar[ConfigDict] = ConfigDict(populate_by_name=True)

    user_id: str | None = None
    organization_id: str | None = None
    authorization_url: str | None = None
    code_challenge: str | None = None
    code_verifier: str | None = None
    state: str | None = None
    scopes: list[str] | None = None
    upstream_metadata: dict[str, Any] | None = None
    error: dict[str, Any] | None = None
    created_at: _dt.datetime | None = None
    updated_at: _dt.datetime | None = None
    completed_at: _dt.datetime | None = None

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> "SupabaseMcpOauthTransaction":
        if isinstance(row.get("scopes"), str):
            row = {**row, "scopes": [row["scopes"]]}
        return cls.model_validate(row)


class SupabaseMcpOauthToken(_schema.McpOauthToken):
    model_config: ClassVar[ConfigDict] = ConfigDict(populate_by_name=True)

    access_token: str | None = None
    refresh_token: str | None = None
    token_type: str | None = None
    scope: str | None = None
    expires_at: _dt.datetime | None = None
    issued_at: _dt.datetime | None = None
    upstream_response: dict[str, Any] | None = None
    organization_id: str | None = None
    user_id: str | None = None

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> "SupabaseMcpOauthToken":
        return cls.model_validate(row)


class SupabaseChatSession(_schema.ChatSession):
    model_config: ClassVar[ConfigDict] = ConfigDict(populate_by_name=True)

    last_message_at: _dt.datetime | None = None
    metadata: dict[str, Any] | None = None
    title: str | None = None
    agent_type: str | None = None
    model: str | None = None
    updated_at: _dt.datetime | None = None
    created_at: _dt.datetime | None = None
    org_id: str | None = None
    agent_id: str | None = None

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> "SupabaseChatSession":
        return cls.model_validate(row)


class SupabaseChatMessage(_schema.ChatMessage):
    model_config: ClassVar[ConfigDict] = ConfigDict(populate_by_name=True)

    metadata: dict[str, Any] | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None
    tokens_total: int | None = None
    created_at: _dt.datetime | None = None
    updated_at: _dt.datetime | None = None

    @property
    def tokens(self) -> int | None:  # pragma: no cover - compatibility shim
        return self.tokens_total

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> "SupabaseChatMessage":
        return cls.model_validate(row)


__all__ = [
    "SupabaseSystemPrompt",
    "SupabaseMcpConfiguration",
    "SupabaseMcpOauthTransaction",
    "SupabaseMcpOauthToken",
    "SupabaseChatSession",
    "SupabaseChatMessage",
]
