name: Build and Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    NEXT_PUBLIC_GUMLOOP_API_KEY: foo
    NEXT_PUBLIC_GUMLOOP_API_URL: foo
    NEXT_PUBLIC_GUMLOOP_USER_ID: foo
    NEXT_PUBLIC_GUMLOOP_FILE_CONVERT_FLOW_ID: foo
    NEXT_PUBLIC_GUMLOOP_REQ_ANALYSIS_FLOW_ID: foo
    NEXT_PUBLIC_GUMLOOP_REQ_ANALYSIS_REASONING_FLOW_ID: foo
    NEXT_PUBLIC_GUMLOOP_TEXT_TO_MERMAID_FLOW_ID: foo
    NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
    NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
    NEXT_PUBLIC_CHUNKR_API_KEY: foo

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Cache Next.js build
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ github.workspace }}/.next/cache
                  # Generate a new cache whenever packages or source files change.
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  # If source files changed but packages didn't, rebuild from a prior cache.
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build --no-lint

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run linting
              run: bun run lint
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Check Prettier version
              run: bun prettier --version

            - name: Debug Prettier configuration
              run: |
                  echo "Prettier configuration files:"
                  find . -maxdepth 2 -name ".prettier*" -type f -exec echo {} \; -exec cat {} \;
                  echo "\n"

            - name: Run prettier check first (without writing)
              run: bun prettier src --write

            - name: Run prettier
              run: bun prettier src --check

            - name: Check for changes
              run: |
                  if ! git diff --quiet; then
                    echo "=== FILES THAT NEED FORMATTING ==="
                    git diff --name-only
                    echo "\n=== DETAILED CHANGES ==="
                    git diff --color
                    echo "\n=== LINE ENDING CHECK ==="
                    git diff | grep -E '[\+\-]$' || echo "No line ending issues detected"
                    echo "\nPrettier detected unformatted files. Please run 'bun prettier src --write' and commit changes."
                    exit 1
                  else
                    echo "No formatting changes detected."
                  fi
