name: Security Audit

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
    schedule:
        # Run security audit daily at 2 AM UTC
        - cron: '0 2 * * *'
    workflow_dispatch:

jobs:
    security-audit:
        runs-on: ubuntu-latest
        name: Security Vulnerability Scan

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.bun/install/cache
                      node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run security audit script
              run: bun run security:audit

            - name: Run npm audit
              run: npm audit --audit-level moderate
              continue-on-error: true

            - name: Check for high/critical vulnerabilities
              run: |
                  if npm audit --audit-level high --json | jq '.metadata.vulnerabilities.high + .metadata.vulnerabilities.critical' | grep -v '^0$'; then
                    echo "❌ High or critical vulnerabilities found!"
                    npm audit --audit-level high
                    exit 1
                  else
                    echo "✅ No high or critical vulnerabilities found"
                  fi

            - name: TypeScript type check
              run: bun run type-check

            - name: ESLint security check
              run: bun run lint

            - name: Build verification
              run: bun run build

            - name: Upload security report
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: security-report
                  path: |
                      npm-audit.json
                      security-audit.log
                  retention-days: 30

    dependency-review:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Dependency Review
              uses: actions/dependency-review-action@v4
              with:
                  fail-on-severity: moderate
                  allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
