name: Sync Fork

on:
    workflow_run:
        workflows: [Build and Lint]
        # branches:
        #     - main
        types: [completed]

env:
    GH_USERNAME: ${{ secrets.FORK_GH_USERNAME }}
    GH_TOKEN: ${{ secrets.FORK_GH_TOKEN }}

jobs:
    sync-fork:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Git
              env:
                  GH_EMAIL: ${{ secrets.FORK_GH_EMAIL }}
              run: |
                  git config --global user.name $GH_USERNAME
                  git config --global user.email $GH_EMAIL

            - name: Login to GitHub
              run: |
                  gh auth status

            - name: Clone fork repository
              env:
                  FORK_REPO: ${{ secrets.FORK_REPO }}
              run: |
                  git clone https://github.com/${FORK_REPO}.git fork-repo
                  cd fork-repo
                  echo "Successfully cloned fork repository"

            - name: Add upstream remote
              working-directory: ./fork-repo
              run: |
                  git remote add upstream https://github.com/${{ github.repository }}.git
                  echo "Added upstream remote"

            - name: Fetch upstream changes
              working-directory: ./fork-repo
              run: |
                  git fetch upstream
                  echo "Fetched upstream changes"

            - name: Sync main branch
              working-directory: ./fork-repo
              run: |
                  git checkout main
                  git merge upstream/main --no-edit
                  echo "Merged upstream changes into main branch"

            - name: Push changes to fork
              working-directory: ./fork-repo
              run: |
                  git push origin main
                  echo "Fork successfully synced with upstream repository"
